add smoke testing

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -68,6 +68,30 @@ jobs:
         run: |
           docker build . -t ${{ vars.DOCKER_HUB_USERNAME }}/myfinance:latest
 
+      - name: Start image
+        run: docker compose up -d
+
+      - name: Smoke Test
+        run: |
+          success=false
+          for i in {1..10}; do
+            if  curl -s http://localhost:8080/actuator/health | grep -q '{"status":"UP"}'; then
+              echo "Application is up and running."
+              success=true
+              break
+            fi
+            echo "Application is not up yet after $i retries. Retrying in 5 seconds..."
+            sleep 5
+          done
+          
+          if [[ "$success" == "false" ]]; then
+            echo "Failed to start application after $i retries."
+            exit 1
+          fi
+          
+          if curl -sSf http://localhost:8080/actuator/health | grep -q '{"status":"UP"}'
+      
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
